apiVersion : apps/v1
kind: Deployment
metadata:
  name: amitbhatikpipelinejs 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amitbhatikpipelinejs
  template:
    metadata:
      labels:
        app: amitbhatikpipelinejs 
    spec:
      containers:
        - name: amitbhatikpipelinejs 
          image: devopsacramit.azurecr.io/amitbhatikpipelinejs
          ports:
          - containerPort: 8080